from datetime import UTC, datetime
from hashlib import sha1

from ai_shorts.schemas.research_report import ResearchReport


class ChatGPTDeepResearchAdapter:
    """Foundation adapter for future OpenClaw-backed ChatGPT Deep Research."""

    async def research(self, query: str) -> ResearchReport:
        normalized = query.strip()
        if not normalized:
            msg = "research query is required"
            raise ValueError(msg)

        report_id = sha1(f"chatgpt:{normalized}".encode()).hexdigest()[:12]
        return ResearchReport(
            id=f"chatgpt_{report_id}",
            title=f"Research brief: {normalized}",
            summary="Placeholder brief generated by the Phase 1 foundation adapter.",
            body_markdown=(
                f"# Research brief: {normalized}\n\n"
                "This placeholder will be replaced by OpenClaw-backed ChatGPT Deep Research."
            ),
            sources=[],
            created_at=datetime.now(UTC),
        )
