from datetime import UTC, datetime
from hashlib import sha1

from ai_shorts.schemas.research_report import ResearchReport


class GrokDeepSearchAdapter:
    """Foundation adapter for future Grok DeepSearch integration."""

    async def research(self, query: str) -> ResearchReport:
        normalized = query.strip()
        if not normalized:
            msg = "research query is required"
            raise ValueError(msg)

        report_id = sha1(f"grok:{normalized}".encode()).hexdigest()[:12]
        return ResearchReport(
            id=f"grok_{report_id}",
            title=f"DeepSearch brief: {normalized}",
            summary="Placeholder brief generated by the Phase 1 foundation adapter.",
            body_markdown=(
                f"# DeepSearch brief: {normalized}\n\n"
                "This placeholder will be replaced by Grok DeepSearch results."
            ),
            sources=[],
            created_at=datetime.now(UTC),
        )
